version: '3.9'

services:
  cache:
    container_name: cache-test
    image: bitnami/redis:7.0.5
    ports:
      - ${CACHE_PORT}:6379
    environment:
      ALLOW_EMPTY_PASSWORD: true
    volumes:
      - cache-data-test:/bitnami/redis/data
volumes:
  cache-data-test:
