version: '3.9'

services:
  cache:
    container_name: cache-test
    image: redis:7.0.7-alpine
    ports:
      - ${CACHE_PORT}:6379
    volumes:
      - cache-data-test:/bitnami/redis/data
volumes:
  cache-data-test:
